### ISSUE TITLE
Bad character encoding on error responses

### ISSUE THREAD

**Issue by jwilander** [Rebilly/ReDoc#153]
Not sure if this is specifically a Redoc issue but posting here just in case.

The dropdown or little chevron symbol for error response codes seems to be encoding incorrectly on my instance.

<img width="678" alt="screen shot 2016-12-06 at 7 50 27 am" src="https://cloud.githubusercontent.com/assets/2672098/20926253/58120a68-bb89-11e6-834c-fddb413fa8b9.png">

You can see it live [here](https://api.mattermost.com/#tag/files%2Fpaths%2F~1teams~1%7Bteam_id%7D~1files~1upload%2Fpost) and the YAML is available [here](https://api.mattermost.com/static/mattermost-openapi.yaml).

Any ideas?

**Comment by IvanGoncharov** [comment]
@jwilander Demo with your spec looks fine: http://rebilly.github.io/ReDoc/?url=https://api.mattermost.com/static/mattermost-openapi.yaml

![image](https://cloud.githubusercontent.com/assets/8336157/20930296/9f5bbb3e-bbd5-11e6-87fa-69652f74149d.png)

Can you please update to the v1.6.1 (latest), because currently, you are using v1.5.2
If it doesn't help please check that your server use UTF-8, we had similar issue: #29

**Comment by jwilander** [comment]
Thanks @IvanGoncharov, I'll try that

**Comment by jwilander** [comment]
Changing `Content-Type` from `text/html` to `text/html; charset=utf-8` fixed the issue. Thanks for your help!

**Comment by IvanGoncharov** [comment]
@jwilander You're welcome.
