### ISSUE TITLE
JSON request/response examples do not display the root object

### ISSUE THREAD

**Issue by andrewjtech123** [Rebilly/ReDoc#156]
We have an important issue with root object not being displayed in JSON.  The alpha partners of our draft order api endpoint are trying to copy paste json request examples and they are failing.

"root of the object is not displayed. If user were to copy/paste this into body of a api client request it would fail without the root object of the JSON."

**Comment by RomanGotsiy** [comment]
@andrewjtech123 can you add more details? e.g. what is expected and what you get.
Thanks

**Comment by andrewjtech123** [comment]
Please see 201 created response for Create Draft Order

https://andrewjtech123.github.io/rebilly-validschema/

As you can see it starts out with the root object.

![draft order root](https://cloud.githubusercontent.com/assets/6719991/20978809/44c99d96-bc78-11e6-85d8-e18cddcf99ff.png)

maybe we can use a field like response examples to override the json request example with our own JSON ?

**Comment by RomanGotsiy** [comment]
I've just checked your spec and the docs. ReDoc displays request samples exactly according to the schema. You don't have root object in your schema. That's why it is not displayed in the sample.

It is displayed as you need it in response because you use response samples.

You can workaround request in redoc the same way by using `example` value on `schema` object.
BUT I suggest you to fix your spec as it may be used not only with ReDoc but with other swagger tools.

Let me know if you need assistance with fixing your spec.

**Comment by RomanGotsiy** [comment]
I will close this issue.
Feel free to reopen/ask questions here.
