### ISSUE TITLE
Start with response list expanded

### ISSUE THREAD

**Issue by agallou** [Rebilly/ReDoc#165]
First, thanks for Redoc, your project is very usefull to us.

When I give our client the link to our API doc, I always say something like "You must click on '200 Products Response' to display the response content". So it could be usefull to have those expanded by default.

I'm not used to developp with angular, but if it's a feature that you are ready to have on the projet, i'll try to make a PR.

So, how could such a functionnality be implemented functionnaly ? 
* an attribute when including readoc like "responses-expanded" (that expands all responses or all 2xx responses)
* a boolean x-expanded key on the swagger spec on each response (that allows users to choose witch responses must be expanded

after that, did you have any hints on to implement that technically ? (espacilly with the lazy json-schema) (I will probably be something around here : https://github.com/Rebilly/ReDoc/blob/5bd0ac2d11d01c91fb75c8b98418b35c29e65f22/lib/components/ResponsesList/responses-list.html#L23)

**Comment by RomanGotsiy** [comment]
@agallou thanks for using ReDoc and even reading its code :)

I should explain why I have hidden all the responses under the zippy. This was done due to performance limitations. For specs with huge number of endpoints response schemas generation took lot of time so I hidden it under the zippy and made lazy-rendered.

I'm OK with adding such option to ReDoc though. I vote for having ReDoc attribute against `x-expanded` in the spec.

I was going to provide you with a hints of how to implement this but while checking code implemented it itself: [commit](https://github.com/Rebilly/ReDoc/commit/95f2da8b97c9cffb228a37459557baf2133c952b). It appeared to be an easy change :)

Closing this issue.
The new functionality will be available in the next release till the end of the week

**Comment by agallou** [comment]
:+1:  that's awesome. thanks for the feature.

**Comment by RomanGotsiy** [comment]
new version `1.6.3` with the feature is available
