### ISSUE TITLE
OpenAPI 3.0 support?

### ISSUE THREAD

**Issue by willdady** [Rebilly/ReDoc#207]
Are there any plans to add support for OpenAPI 3.0? It looks like the spec is settling with the first implementer draft dropping at the end of February.

https://www.openapis.org/blog/2017/01/24/a-new-year-a-new-specification

**Comment by RomanGotsiy** [comment]
@willdady,
yes, there are plans to support it.
But I am not sure about timeframe. There are a lot of changes in the version + a few things I am not sure how to implement at the moment (`oneOf`, `anyOf`, `not`, etc)

**Comment by eitan101** [comment]
+1 for the "oneOf".
I currently use [json-editor](https://github.com/jdorn/json-editor) to present read-only form and it supports "oneOf", but for documentation purposes is much nicer.

**Comment by LakshmananVignesh** [comment]
@RomanGotsiy Hi its very nice to use ReDoc any update on OpenApi 3.0 support

**Comment by RomanGotsiy** [comment]
@LakshmananVignesh it's definitely on the roadmap but I'm quite busy at the moment with other huge feature for ReDoc now so can't give you any ETA.
Once I finish with that, will let you know.

**Comment by avkonst** [comment]
Duplicating comment, but will post it here too:

Discriminator from v2 of the spec does not make things simple and will be conflicting with the anyOf, oneOf, allOff features, once implemented. And it would be easier to get rid of the discriminator. I have removed it from my APIs and use standard JSON-schema xxxOf features. Redoc may render a nested section per each xxxOf declaration with a headline indicating type of xxx constraint and with "carousel-like" (horizontal) scroller to slide through subtype definitions from inside of the xxxOf. This would be simpler, because it would not require any schema introspection to determine discriminator-like field, would not require "select" based field and reactive response to it. The ReDoc view of sections would map one to one definitions in the JSON-schema, what would be easier to understand for API consumers. I would love to have such a behavior of ReDoc. What do you think?

**Comment by RomanGotsiy** [comment]
@avkonst thanks for the idea 🙌 
It sounds very reasonable.

I am about to start huge refactoring toghether with implementing OpenAPI 3.0 support so I will consider you idea!

**Comment by avkonst** [comment]
Great! Thank you for the great work! I think simplicity matters. My users know about JSON-schema - it is the first thing they are dealing with when define their data model for the API. So having the documentation mapped one to one with JSON-schema is very clear and very understood. OpenAPI spec was needed as an intermediate step to the rendered browsable documentation. I have chosen ReDoc as a documentation tool 6 months ago because I believed it has got the potential to go in the right direction. I can help you with testing and trying your refactored version and run it with my users to gather feedback, if it helps. Let me know.

**Comment by jmauerhan** [comment]
I would also really like support for Open Api 3. If there's anything I can do to help out, IE tickets that could be worked - I would be more than happy to do so.

**Comment by andrehagemeier** [comment]
any news on 3.0 support?

**Comment by RomanGotsiy** [comment]
@jmauerhan will come together with https://github.com/Rebilly/ReDoc/issues/327. Maybe some feature will be missing at the beginning

@andrehagemeier thanks! There will definitely be some work after https://github.com/Rebilly/ReDoc/issues/327. If you are still willing to help out I will create tickets as soon as I finish React rewrite.

**Comment by RomanGotsiy** [comment]
Just noticed there are two issues about OpenAPI 3 support.
Closing this in favor of #312
