### ISSUE TITLE
Tag not shown if not in tagGroup

### ISSUE THREAD

**Issue by bartkummel** [Rebilly/ReDoc#215]
When using the `x-tagGroups` feature, tags that are not in a tagGroup are not shown at all. I would at least expect a warning. But perhaps it is even better to create a default tagGroup automatically, where all ungrouped tags are added to implicitly.

**Comment by RomanGotsiy** [comment]
@bartkummel there should be a warning in browser console saying which tags are not shown at all
![image](https://cloud.githubusercontent.com/assets/3975738/23408904/5984db9c-fdd2-11e6-97d0-8cd53f9c4ed3.png)

Regarding default `tagGroup`, I do not thing it is a good solution because it it is not clear e.g. how to name it, where to put it (on the beginning or at the end). And I don't want to introduce options like `defaultGroupTitle`, `defaultGroupPosition`.

I will add warning not only to console but also to the top of the page. Do you think it would be an appropriate solution?

**Comment by bartkummel** [comment]
I think adding a warning to the page is an appropriate solution. Perhaps it's a good idea to add a warning to the documentation as well, such as: "If you are going to use `x-tagGroups`, please make sure you add all tags to a group, since a tag that is not in a group, will not be displayed at all!"

**Comment by Paxa** [comment]
It wouldn't hurt to show ungrouped content below, I don't think anyone want to include content in api spec but not show it in the web ui (which happens when tag is not in the list), if someone need hiding content with tagGroup please share a use case

I guess more often it would be "suddenly gone" when we update docs and not update tagGroup section :(((
