### ISSUE TITLE
custom CSS

### ISSUE THREAD

**Issue by ranjapri** [Rebilly/ReDoc#241]
Hi ReDoc team,
Is there any way to apply custom css in ReDoc? I tried applying in index.html of ReDoc but that is getting overridden by ReDoc styles.

Regards.

**Comment by jsmartfo** [comment]
This is similar to #144

You can override certain styles you would just have to use the `important` operator a lot

```
.menu-content {
    background-color: #ffff00 !important;
}
```

**Comment by RomanGotsiy** [comment]
@jsmartfo thanks for answering!
CSS is now getting overridden by ReDoc as it uses attributes selectors.

Instead of having `important` try to prefix all your css rules with e.g. `redoc[spec-url]`. It should increase specifity of css selectors and do the trick.

During the next month I am going to refactor all the css and this issue should not happen in the future

**Comment by ranjapri** [comment]
Thanks Roman and Jsmartfo,

One clarification, do i need to specify the css file like following in index.html?
 <redoc spec-url="customstyle.css" ></redoc>
or need to modify the css file itself and modify the style (could you please provide an example for this? how to prefix the css rule?)

Regards,

**Comment by RomanGotsiy** [comment]
@ranjapri `spec-url` is for providing swagger spec not css file.

You should add your css into head of the html page. Taking quick example from readme:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>ReDoc</title>
    <!-- needed for adaptive design -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
      body {
        margin: 0;
        padding: 0;
      }
    </style>
    <link rel="stylesheet" href="YOUR CSS LINK HERE">
  </head>
  <body>
    <redoc spec-url='http://petstore.swagger.io/v2/swagger.json'></redoc>
    <script src="https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js"> </script>
  </body>
</html>
```

**Comment by ranjapri** [comment]
Thank you so much Roman,
It works but writing important for all styles or even prefixing  is troublesome. Will the CSS work seamlessly after the code refactoring?

Regards.

**Comment by RomanGotsiy** [comment]
@ranjapri yes, it will

**Comment by ChazzMaTazz** [comment]
Where is the .css that Redoc itself is using. I don't see it in Github.

**Comment by debri174** [comment]
Is custom CSS like this supported in [redoc-cli](https://github.com/Rebilly/ReDoc/blob/master/cli/README.md)?

**Comment by RomanGotsiy** [comment]
@debri174, no, redoc-cli is using redoc@2.0.0-alpha.x which is a complete rewrite so this css doesn't work
To customize it you can use the `theme`. Check out [README](https://github.com/Rebilly/ReDoc#configuration) for details

**Comment by ShaneGMamet** [comment]
Could someone please confirm;
- If i've wanting to use custom styling (for any / every thing), I would need to stick to v1.x.x for now? (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js) rather than the newer v2 (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js)?

Seems that, using the v1.x.x reference I can get the styling to work (external link and in place styling), however, if I change to v2, nothing renders? 
@RomanGotsiy
