### ISSUE TITLE
Visualize deprecated operations

### ISSUE THREAD

**Issue by pgolm** [Rebilly/ReDoc#286]
Hi

I've tried to mark some operations as deprecated like it's [documented](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operation-object) for operation objects. This option is not handled in ReDoc. Swagger UI rendered it with `text-decoration: line-through`. 

<img width="747" alt="bildschirmfoto 2017-06-21 um 11 15 35" src="https://user-images.githubusercontent.com/1444194/27376641-0a98ec86-5673-11e7-947d-180c8968728e.png">

Maybe we could add this too. What do you think?

**Comment by Lytkini** [comment]
+1

**Comment by avkonst** [comment]
I faced similar needs, however, I have got deprecation on per field basis, not per operation. Also, deprecation style may require rendering of a note on what the alternative / new method which replaces the deprecated stuff.

**Comment by jimmyjames** [comment]
+1

I'd be fine with a simple "Warning: Deprecated" text beneath the operation header, but before the description. I think the schema object ReDoc already supports this, so should just be a matter of passing it through the controller/view and agreeing on style/text to add.

I think the suggested/new operation to use (if applicable) would need to be in the operation description itself, since the `deprecated` field is just a boolean (though .
