### ISSUE TITLE
Cannot find module '../compiled/lib/app.module.ngfactory'.

### ISSUE THREAD

**Issue by monolithed** [Rebilly/ReDoc#362]
```
webpack: Compiled successfully.

[at-loader] Checking finished with 1 errors
[at-loader] ./lib/bootstrap.ts:4:36 
    TS2307: Cannot find module '../compiled/lib/app.module.ngfactory'. 
```

```
➜ uname -a
Darwin msk-wifi-20fap6-a_abashkin-a.abashkin.mail.msk 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

**Comment by Philip-Nunoo** [comment]
Any solutions?

**Comment by RomanGotsiy** [comment]
@monolithed, @Philip-Nunoo this message is a known issue, but it shouldn't affect compilation process.
The file it complains it can't find is not required for dev run, and for the production build, it is generated.

If this error message distracts you just run `npm run ngc` once and it will disappear in the next builds.

This issue will be fixed with migrating to React happening soon.
