### ISSUE TITLE
Can't $ref parameters

### ISSUE THREAD

**Issue by iocast** [Rebilly/ReDoc#377]
Is is possible to have `$ref` parameters?

When I try [this example](https://github.com/swagger-api/swagger-editor/issues/182#issuecomment-57023733) the parameters are not displayed.

Thanks

**Comment by RomanGotsiy** [comment]
@iocast,because this example is not correct. Each `path` parameter [MUST correspond](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-7) to the associated path segment:
![image](https://user-images.githubusercontent.com/3975738/32741617-7cec54a4-c8af-11e7-80f2-75a7ad698675.png)

The correct example would be:

```yaml
swagger: 2.0
info:
  version: "1.0.0"
  title: petstore
parameters:
  productId: 
       name: productId
       in: path
       type: string
       required: true
paths:
  /users/{productId}: # <----- change here
    get:
      parameters:
        -
          $ref: '#/parameters/productId'
      responses:
        "200":
          description:  Describe the 200 response in more detail
```
Here is the link to ReDoc demo with working example: http://rebilly.github.io/ReDoc/?url=https://gist.githubusercontent.com/RomanGotsiy/7b582b6bac7e70b884b0b6143494827a/raw/d7563dc84ad7743b83ff24cf26b7d49fdddf240e/it-works.yaml

**Comment by bkleef** [comment]
@RomanGotsiy so it's not possible to add `limit` until you add them like `/users/{limit}`? What about [reusableParameters.json](https://github.com/OAI/OpenAPI-Specification/blob/master/fixtures/v2.0/json/resources/reusableParameters.json) as mentioned [here](https://stackoverflow.com/questions/27005105/swagger-openapi-use-ref-to-pass-a-reusable-defined-parameter)?
