### ISSUE TITLE
Feature request: Ability to hide internal paths, operations, parameters etc.

### ISSUE THREAD

**Issue by shreyas-agnihotri** [Rebilly/ReDoc#387]
Need ability to hide internal paths, operations, parameters etc in generated ReDoc documentation.

Something similar to what openapi-filter does: https://github.com/Mermade/openapi-filter
It would be so cool if this was baked into ReDoc.

**Comment by drewish** [comment]
Since you can download the full file using the link at the top of the page it would probably be better to do any filtering on the file before you post it.

**Comment by RomanGotsiy** [comment]
@shreyas-agnihotri thanks for the long reply.

@drewish Thanks for answering! That's what I wanted to answer! Just adding build step would be better.

I think such features should leave as an external tool and not be merged into ReDoc.
btw if you don't want to introduce any build step you can try running https://github.com/Mermade/openapi-filter in the browser before ReDoc using ReDoc API and passing in object instead of URL: https://github.com/Rebilly/ReDoc#advanced-usage

**Comment by geoffreywiseman** [comment]
With the support for extensions already built in, I'd love to be able to filter with x-internal in openapi documentation published with redoc, I agree. Mostly, I want this for things that are essentially feature-flagged, so I have features that aren't public yet and documentation that isn't yet public, and later enable those features and remove the internal flag and republish the docs.

It can definitely be done as a separate step, it's just more work for me, and it feels like it fits in with the  extension model.
