### ISSUE TITLE
Importing to PDF

### ISSUE THREAD

**Issue by ksachdeva11** [Rebilly/ReDoc#391]
Is there a way we can import the documentation to a PDF ?

**Comment by bartfeenstra** [comment]
Importing anything from any PDF is usually hard, because PDF's don't structure their data very well. The reason ReDoc works the way it does, is because Swagger/OpenAPI are structured API documentation, formatting the specification in such a way that a tool like ReDoc can read it. This is impossible with PDFs, due to the fact PDFs are meant for free-form data.

**Comment by RomanGotsiy** [comment]
Unfortunately, This is out of the scope of this project as it has interactive features which are not possible in PDF.
