### ISSUE TITLE
Unable to resolve $ref pointer "file:///openapi.json"

### ISSUE THREAD

**Issue by lalib** [Rebilly/ReDoc#587]
Hi there,

I am experimenting ReDoc locally but i got the following error message when i try to use the api spec locally.

```
Something went wrong...
Unable to resolve $ref pointer "file:///openapi.json"
Stack trace
SyntaxError: Unable to resolve $ref pointer "file:///openapi.json"
    at Function.syntax (file:///node_modules/redoc/bundles/redoc.standalone.js:55:33727)
    at file:///node_modules/redoc/bundles/redoc.standalone.js:73:35706

ReDoc Version: 2.0.0-alpha.30 
Commit: ea2210a
```

I have found the following PR as merged but i am not sure if it is released or not.

https://github.com/ikalnytskyi/sphinxcontrib-redoc/pull/14

Also I found the following issues:

https://github.com/Rebilly/ReDoc/issues/149
https://github.com/Rebilly/ReDoc/issues/390
https://github.com/Rebilly/ReDoc/issues/113

Is it not supported to load apis locally?

Best,

Bilal

**Comment by RomanGotsiy** [comment]
@lalib yes, there is no way ReDoc can load the spec from local file system due to browser security restrictions. All the details are described in #149.

You can use `redoc-cli` [bundle command](https://github.com/Rebilly/ReDoc/tree/master/cli#usage) which works pretty similar to  ikalnytskyi/sphinxcontrib-redoc#14
