### ISSUE TITLE
Webpack Setup

### ISSUE THREAD

**Issue by amcdnl** [Rebilly/ReDoc#79]
Would you be inclined to move off system/jspm to webpack? 

I'm happy to PR back if I can get it working, given angular-cli is doing webpack now I think its a obvious migration option.

**Comment by RomanGotsiy** [comment]
@amcdnl yes, I've been considering this change since I saw [your tweet](https://twitter.com/amcdnl/status/760980156928450560) :)
Your PR would be super useful as I've never used WebPack before. I am finishing upgrading to the latest RC today. Also doing some refactoring.
So if you want to contribute, wait for me to finish this. I will post back here once.

**Comment by amcdnl** [comment]
Haha, nice! Hugeeee jump in perf!

Webpack shouldn't affect any of that, its just the build run. Do you have a time frame for when that would be done?

**Comment by RomanGotsiy** [comment]
> Do you have a time frame for when that would be done?
Yes. Going to finish upgrade and refactor today night (~8-10PM PDT)

> Webpack shouldn't affect any of that, its just the build run.
I think so :)

**Comment by amcdnl** [comment]
Here is a reference for a Webpack setup - https://github.com/swimlane/angular2-data-table

**Comment by RomanGotsiy** [comment]
Will finish it tomorrow. Have some personal troubles + troubles with migrating tests.

**Comment by RomanGotsiy** [comment]
Finally I did it! It took me more time than expected but I'm happy with the result. Dev server is mega fast if compare to my old thing :)
+ no more duplicated modules in `node_packages` and `jspm_packages`
@amcdnl thanks for the suggestion!
