### ISSUE TITLE
Images are not rendered correctly

### ISSUE THREAD

**Issue by monolithed** [Rebilly/ReDoc#790]
### Source:

```yaml
tags:
  - name: Рабочий процесс
    description: |
      Задача ставиться в JIRA c типом API, со следующим рабочим процессом (workflow):

      <div align="center">
        ![Workflow](../static/workflow.png#center)
      </div>
```

### Result:

```html
<div align="center">
        ![Workflow](../static/workflow.png#center)
</div>
```

<img width="665" alt="screen shot 2019-01-21 at 17 23 23" src="https://user-images.githubusercontent.com/803674/51480118-4e2ca680-1da1-11e9-8bbb-71de1a705464.png">

That problem is actual after updating 2.0.0-alpha.38 to 2.0.0-rc.1

**Comment by RomanGotsiy** [comment]
This is correct behavior according to CommonMark spec which is used by OpenAPI spec: [see playground link](https://spec.commonmark.org/dingus/?text=%D0%97%D0%B0%D0%B4%D0%B0%D1%87%D0%B0%20%D1%81%D1%82%D0%B0%D0%B2%D0%B8%D1%82%D1%8C%D1%81%D1%8F%20%D0%B2%20JIRA%20c%20%D1%82%D0%B8%D0%BF%D0%BE%D0%BC%20API%2C%20%D1%81%D0%BE%20%D1%81%D0%BB%D0%B5%D0%B4%D1%83%D1%8E%D1%89%D0%B8%D0%BC%20%D1%80%D0%B0%D0%B1%D0%BE%D1%87%D0%B8%D0%BC%20%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81%D0%BE%D0%BC%20(workflow)%3A%0A%0A%3Cdiv%20align%3D%22center%22%3E%0A%20%20!%5BWorkflow%5D(..%2Fstatic%2Fworkflow.png%23center)%0A%3C%2Fdiv%3E).

The previous version of ReDoc used the old version of `marked` markdown parser which was not spec-compliant.

In order to render image inside of `html` block use html tags:

```
<div align="center">
  <img alt="Workflow" src="../static/workflow.png#center" />
</div>
```
