### ISSUE TITLE
Upgrade to Typescript 2.0

### ISSUE THREAD

**Issue by amcdnl** [Rebilly/ReDoc#80]
TypeScript 2.0 is way better and nixes the need for `typings`.

**Comment by RomanGotsiy** [comment]
Frankly speaking, this is my first project using Typescript and I migrated to typescript in the process (initially it was ES6 - that's why I have babel dependencies and that's why codebase is poorly typed)

I believe moving to TS 2.0 can be done together with https://github.com/Rebilly/ReDoc/issues/79.

Can't it?

**Comment by amcdnl** [comment]
Yup :)
