### ISSUE TITLE
Multiline description with json

### ISSUE THREAD

**Issue by pedro-teixeira** [Rebilly/ReDoc#82]
I'm adding descriptions with `\n` but they are not interpreted.

Example:

```json
{
  "basePath": "/v1",
  "consumes": [
    "application/json"
  ],
  "host": "test.com",
  "info": {
    "description": "Test\nTest",
    "title": "Test",
    "version": "1"
  }
}
```

Am I doing something wrong or is this really an issue?

**Comment by RomanGotsiy** [comment]
@pedro-teixeira this is an issue.
Will try to include this fix in the next release.

**Comment by pedro-teixeira** [comment]
Thanks @RomanGotsiy

**Comment by pedro-teixeira** [comment]
@RomanGotsiy thank you for the quick fix! I saw you created a new release (v1.1.1) but I think the GitHub pages release is missing.

**Comment by pedro-teixeira** [comment]
Now it's there, it seems to be working fine! Thank you again.

**Comment by RomanGotsiy** [comment]
@pedro-teixeira yes, GitHub pages release is deployed by CI so it requires some time

**Comment by RomanGotsiy** [comment]
@pedro-teixeira I'm sorry but I have to revert this fix.
According to the Swagger spec description field is [GitHub Flavored Markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown).

So when you logged this issue I had tried adding a new line here in comments to this issue and it worked: line break was added. So that's why I considered this to be a bug. But now I've checked the same thing on README file and this doesn't work there: a new line is not line break there. I have also checked how SwaggerUI handles this and it doesn't treat newlines as page breaks. As most of the users test their specs on SwaggerUI I don't want to introduce incompatibility here.

After I revert this fix you can achieve what you need by the following (according to the markdown [spec](http://daringfireball.net/projects/markdown/syntax#p))

1) add two new lines: `"description": "Test\n\nTest"...` (it will create a new paragraph)
2) end a line with two or more spaces: `"description": "Test  \nTest"..`
3) add HTML hard break: `"description": "Test<br>Test"...` (HTML tags are supported by GFM)

Let me know if you are ok with this.

**Comment by pedro-teixeira** [comment]
@RomanGotsiy works for me! Thank you!

**Comment by christopher-bonitz** [comment]
I think I found this bug in another element, can I request to reopen this issue? the fix is most likely very similar.
I'm finding missing new lines on model descriptions/summery


"Horse": {
          "terminalId": {
            "type": "string",
            "description": "Identification bla bla bla. \r\nIt must be possible to bla bla bla.\r\nThis information is only required for bla bla bla",
            "nullable": true
          }
      }

Thanks a lot
