### ISSUE TITLE
'Unterminated String Constant' on build

### ISSUE THREAD

**Issue by brymon68** [Rebilly/ReDoc#879]
When trying to build via Parcel, I am receiving the following error: 

/path/to/my/project/node_modules/redoc/bundles/redoc.lib.js:6305:171996: Unterminated string constant (6305:171996)

My package.json for my project looks like: 
```
{
  "name": "ui",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@material-ui/core": "latest",
    "@material-ui/icons": "latest",
    "autoprefixer": "7.1.6",
    "axios": "^0.18.0",
    "babel-core": "7.3.4",
    "babel-eslint": "7.3.4",
    "babel-jest": "20.0.3",
    "babel-loader": "8.0.5",
    "babel-preset-react-app": "^3.1.1",
    "babel-runtime": "latest",
    "case-sensitive-paths-webpack-plugin": "2.1.1",
    "css-loader": "0.28.7",
    "date-fns": "^1.29.0",
    "events": "latest",
    "fs-extra": "3.0.1",
    "history": "^4.7.2",
    "jquery": "^3.3.1",
    "material-ui": "latest",
    "mobx": "^5.9.4",
    "mui-datatables": "^2.0.0-beta-39",
    "notistack": "^0.4.0",
    "promise": "8.0.1",
    "react": "^16.8.4",
    "react-broadcast": "^0.6.1",
    "react-dev-utils": "^5.0.1",
    "react-dom": "^16.8.4",
    "react-frame": "latest",
    "react-json-view": "latest",
    "react-router-bootstrap": "latest",
    "react-router-dom": "latest",
    "react-swipeable-views": "^0.13.0",
    "react-table": "^6.5.1",
    "recompose": "^0.26.0",
    "redoc": "^2.0.0-rc.4",
    "resolve": "1.6.0",
    "style-loader": "0.19.0",
    "styled-components": "^4.2.0",
    "url-loader": "0.6.2"
  },
  "scripts": {
    "build": "rm -rf ../public/* && parcel build src/index.html --no-source-maps --out-dir ../public/ --no-cache",
    "watch": "rm -rf ../public/* && parcel watch src/index.html --out-dir ../public/ --no-cache"
  },
  "babel": {
    "presets": [
      "react-app"
    ]
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "devDependencies": {
    "parcel-bundler": "^1.12.3"
  }
}
```

Node version: 8.11.3

Any idea what could be happening here?

**Comment by RomanGotsiy** [comment]
I have no idea. Try opening an issue on Parcel repo.

**Comment by somdoron** [comment]
@brymon68 did you find a solution?

**Comment by brymon68** [comment]
@somdoron  - Nope. Pretty disappointed too. I ended up using the docker container but wasn't happy about it

**Comment by owap** [comment]
Just want to report that I'm using Parcel and still getting this issue. It errors when attempting to create a worker:

```
🚨 Build Error

/Users/apierce/code/work/api-docs-ui/node_modules/redoc/bundles/redoc.lib.js:6393:196021: Unterminated string constant (6393:196021)
  6391 | 				var methods = ["add","done","toJS","load","search"]
  6392 | 				module.exports = function() {
> 6393 | 					var w = new Worker(URL.createObjectURL(new Blob(["/*!\n * ReDoc - OpenAPI/Swagger-generated API Reference Documentation\n * -------------------------------------------------------------\n *   Version: \"2.0.0-rc.14\"\n *   Repo: https://github.com/Redocly/redoc\n */\n/******/ (function(modules) { // webpackBootstrap\n/******/ \t// The module cache\n/******/ \tvar installedModules = {};\n/** [TRUNCATED]
```

I added the `[TRUNCATED]` myself because the comment was too long to post.

**Comment by yjimk** [comment]
Did a very light dig on what might be happening in here as I ran into it myself when trying to run redoc with parcel

The error maps to this line in the source: https://github.com/Redocly/redoc/blob/11cc4c4c3e04a7e5bf3a9ebba20d10fa882a49e5/src/services/models/ApiInfo.ts#L36

```
const blob = new Blob([JSON.stringify(this.parser.spec, null, 2)], {
        type: 'application/json',
      });
```

When this is compiled and included in node_modules as `/bundles/redoc.lib.js` the line generated (ln. 6440) is super long and contains unescaped closing characters `"`.

Here's a snippet
`var w = new Worker(URL.createObjectURL(new Blob(["/*!\n * ReDoc - OpenAPI/Swagger-generated API Reference Documentation\n * -------------------------------------------------------------\n *   Version: \"2.0.0-rc.23\"\n *   Repo: https://github.com/Redocly/redoc\n */\n/******/ (function(modules) { ...`

VSCode won't actually show me the whole line, but seems invalid. this line is also unrelated to parcel.

My guess is that parcel triggers the if block at runtime, other bundlers don't, otherwise everyone would see the issue.

This is on a fresh install of redoc v2.0.0-rc.23, Node 12, npm 6.
