### ISSUE TITLE
openapi tags splitting?

### ISSUE THREAD

**Issue by luvwinnie** [Rebilly/ReDoc#881]
i have a path with tags object however the tag splitting.
it shows below.
<img width="252" alt="Screen Shot 2019-04-03 at 12 27 16" src="https://user-images.githubusercontent.com/13714992/55451047-43498a00-560c-11e9-9a03-ef06c660341e.png">

How can i fix this?
the swagger is using openapi 3
`"paths": {
    "/random": {
      "post": {
        "description": "POST /form",
        "summary": "Test",
        "tags": "Reference",
        "responses": {
          "200": {
            "examples": {
              "imageData": [{
                "test": "test"
              }]
            },
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Pet"
                }
              }
            }
          }
        }
      }
    }
  }`

**Comment by nanov** [comment]
```tags``` should be an array.

**Comment by luvwinnie** [comment]
@nanov Thanks for reply! I'm able the resolve this problem! Wouldn't it be great if it shows an error with the tags? It shows nothing about it currently, or the other version of ReDoc shows `e.filter is not a function`

**Comment by nanov** [comment]
I am not the developer of ReDoc.
The message from the other version is also a "coincidence", because a filter method is used on the array, so it produces an error. I guess type checking could be easily done, the question is if it's really needed. I would validate my schema with [something like that](https://github.com/APIDevTools/swagger-cli) before deploying.

**Comment by RomanGotsiy** [comment]
@luvwinnie validate your spec before ReDoc. ReDoc intentionally doesn't bundle in a validator to save bundle size.
