### ISSUE TITLE
Discriminators can't share the same mapping for different values

### ISSUE THREAD

**Issue by mramato** [Rebilly/ReDoc#883]
If a discriminator mapping associates the same schema with 2 different values, only he last value is used.  In the below screenshot, Options1, Options2, and Options3 should all be valid choices, but only Options1 and Options3 are shown.

![image](https://user-images.githubusercontent.com/1495196/55816368-1ee42680-5ac0-11e9-8632-965534bac4fe.png)

Here is a reduced test case:
```yaml
openapi: 3.0.2

info:
  title: Discriminators can't share the same mapping for different values
  version: v1
servers:
  - url: http://localhost

paths:
  /v1/items:
    post:
      summary: Create an item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Item"
      responses:
        200:
          description: OK
components:
  schemas:
    Options1:
      type: object
      allOf:
        - $ref: '#/components/schemas/Item'
        - properties:
            options1Property:
              type: boolean
              default: true
    Options2:
      type: object
      allOf:
        - $ref: '#/components/schemas/Item'
        - properties:
            options2Property:
              type: boolean
              default: false
    Item:
      type: object
      discriminator:
        propertyName: optionType
        mapping:
          Options1: "#/components/schemas/Options1"
          Options2: "#/components/schemas/Options2"
          Options3: "#/components/schemas/Options2"
      properties:
        id:
          type: integer
          example: 2194
          readOnly: true
        optionType:
          type: string
          enum:
          - Options1
          - Options2
          - Options3
```

EDIT: Forgot to mention I'm using the official CDN hosted version of v2.0.0-rc.4

**Comment by neluzhin** [comment]
I'm not really sure about that:

> If a discriminator mapping associates the same schema with **2 different values**

Schemas `Options2` and `Options3` are identical (it doesn't matter if your discriminator's mapping keys are different - schemas are identical and both of them point to the same reusable schema defined in `components` section).

Let me explain. You say there may be 2 kind of Pets: Cat and Dog. But when you describe Cat object, your `type` field says it's enum which may hold `cat` or `dog` values. **But that's incorrect!** Your Cat schema may hold only `cat` value, not `dog`! That's why you should create different schemas for Cat and Dog even if their field definitions are identical, but `type` field definition will be different for each Pet.

**Comment by mramato** [comment]
Ultimately for my use case I've done what you suggested and created different identical schemas.

You're explanation makes sense, I just with the spec itself was a little more clear here in terms of mapping being unique.  From a pure schema validation standpoint, non-unique mappings are allowed, which lead to me writing the issue.
