### ISSUE TITLE
Docker Volume not updating automatically

### ISSUE THREAD

**Issue by Gabb1995** [Rebilly/ReDoc#893]
Everytime I deploy a new .yml file I start getting a 404 not found even though its in the same directory and the same volume. Is there maybe some issue with the image that doesn't let me do this and have to restart the service everytime I change the yml file?

Thanks.

**Comment by mtrlitza** [comment]
Hey @Gabb1995,

not sure but I guess I had the same problem. Everytime I changed something in my YAML file, I needed to restart the ReDoc container to see the changes in the UI. According to https://tachingchen.com/blog/container-file-mount-dose-not-update-with-changes-from-host/ it's due to the behavior of how the mounting works.

So mounting the complete directory into a sub-directory and thus changing the `SPEC_URL` works perfectly for me.

For example: instead of using this:
`docker run -ti --rm -p 80:80 -v $(pwd)/project/docs/v1.yaml:/usr/share/nginx/html/v1.yaml -e SPEC_URL=v1.yaml redocly/redoc`

use this:
 `docker run -ti --rm -p 80:80 -v $(pwd)/project/docs/:/usr/share/nginx/html/yaml/ -e SPEC_URL=yaml/v1.yaml redocly/redoc`.

Hope this helps.

Best
Michael

**Comment by RomanGotsiy** [comment]
@mtrlitza thanks for your answer!

Closing this issue!

@Gabb1995 feel free to reopen if you face further issues!

**Comment by Gabb1995** [comment]
Thanks this worked! :)
